version: 2
updates:
  - package-ecosystem: github-actions
    directory: / # パッケージマニフェスト配置先ディレクトリ。ただしGithub actionのみ固定で"/"
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "*"
